apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-service-grpc-api
  namespace: exolve
  description: gRPC API for test-service (Hello and Echo)
  annotations:
   grpc-docs.io/environments: |
      - name: local
        target: 127.0.0.1:50051
        security: insecure
  tags:
    - grpc
    - test-service
    - spine
spec:
  type: grpc-samuel
  lifecycle: experimental
  owner: nornir
  system: exolve/spine-services
 definition:
    $text: https://raw.githubusercontent.com/sokolova11123-art/tech-issues/main/hello.proto
