syntax = "proto3";

package hello;

option go_package = "git.rnd.mtt/oliwio/spine/test-service/pkg/api/hello";

import "google/api/annotations.proto";

// HelloService is a simple service that says hello
service HelloService {
  // SayHello says hello to the given name
  rpc SayHello(HelloRequest) returns (HelloResponse) {
    option (google.api.http) = {
      post: "/v1/hello"
      body: "*"
    };
  }
}

// HelloRequest is the request for the SayHello method
message HelloRequest {
  // Name is the name to say hello to
  string name = 1;
}

// HelloResponse is the response from the SayHello method
message HelloResponse {
  // Message is the hello message
  string message = 1;
}
